name: 'PR Version Check'
description: 'Checks if a version line in a given file has changed in this branch against master'
branding:
  color: red
  icon: alert-triangle

inputs:
  file:
    description: File to check
    required: false
    default: package.json
  branch:
    description: Name of the main branch
    required: false
    default: master

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.file }}
    - ${{ inputs.branch }}
